spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/alm_et?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Ncasla18
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

mercadopago:
  access-token: "APP_USR-6163676715902000-101100-3815e4fe51bb9159d552b49923db09d8-2916747427"
  success-url: "http://localhost:8081/usuario/pago/exitoso"
  failure-url: "http://localhost:8081/usuario/pago/fallido" 
  pending-url: "http://localhost:8081/usuario/pago/pendiente"

server:
  port: 8081